### ISSUE TITLE
nav.py and wait.py through exceptions

### ISSUE THREAD

**Issue by ghost** [mark-thompson/whole-foods-deliverance#13] opened 2020-04-12 19:30 UTC
@mark-thompson here is the traceback. Thanks!

INFO:__main__:No slots found :( waiting...
INFO:__main__:Checking for available slots
INFO:__main__:Found 1 slots: 
Tomorrow::11:00 AM - 1:00 PM
INFO:notify:Alerting user with message: 'Delivery slots found'
ERROR:notify:send_sms() requires a config file at 'conf.toml' with key 'twilio'
ERROR:notify:send_telegram() requires a config file at 'conf.toml' with key 'telegram'
INFO:__main__:Attempting to select slot and checkout
INFO:__main__:Selecting slot: Tomorrow::11:00 AM - 1:00 PM
INFO:nav:Navigating <Route beginning at 'https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html' with 3 stops>
INFO:nav:Navigating <Waypoint ('xpath', "//*[contains(@class, 'ufss-overview-continue-button')]") -> 'gp/buy/payselect/handlers/display.html'>
INFO:nav:Navigated to 'gp/buy/payselect/handlers/display.html'
INFO:nav:Navigating <Waypoint ('id', 'continue-top') -> 'gp/buy/spc/handlers/display.html'>
WARNING:nav:Current URL 'https://www.amazon.com/gp/buy/shipoptionselect/handlers/display.html' does not match target
Handling possible redirect (timeout in 10s)
Traceback (most recent call last):
  File "/Users/aub/Repos/whole-foods-deliverance/nav.py", line 86, in navigate
    EC.url_contains(waypoint.dest)
  File "/Users/aub/Repos/whole-foods-deliverance/env/lib/python3.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 147, in <module>
    site_config.Routes.CHECKOUT.navigate(driver)
  File "/Users/aub/Repos/whole-foods-deliverance/nav.py", line 90, in navigate
    raise e
  File "/Users/aub/Repos/whole-foods-deliverance/nav.py", line 68, in navigate
    self.navigate_waypoint(driver, waypoint, timeout)
  File "/Users/aub/Repos/whole-foods-deliverance/nav.py", line 54, in navigate_waypoint
    "Navigation to '{}' failed".format(waypoint.dest)
nav.NavigationException: Message: Navigation to 'gp/buy/spc/handlers/display.html' failed

**Comment by mark-thompson** [comment] 2020-04-12 19:47
Duplicate of #12

**Closed as completed by mark-thompson** 2020-04-12 19:47 UTC

**Comment by mark-thompson** [comment] 2020-04-13 00:28
@b3ll0v1c let me know if the updated code is working for you
